version: '3'
services:
  web:
    build: .
    ports:
      - "1323:1323"  
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
volumes:
  postgres-data: